rook1_white = Rook.new(0,0,'w')
bishop1_white = Bishop.new(0,1,'w')
knight1_white = Knight.new(0,2,'w')
rook2_white = Rook.new(0,7,'w')
bishop2_white = Bishop.new(0,6,'w')
knight2_white = King.new(0,5,'w')
king_white = King.new(0,4,'w')
queen_white = Queen.new(0,3,'w')

rook1_black = Rook.new(7,0,'b')
bishop1_black = Bishop.new(7,1,'b')
knight1_black = Knight.new(7,2,'b')
rook2_black = Rook.new(7,7,'b')
bishop2_black = Bishop.new(7,6,'b')
knight2_black = King.new(7,5,'b')
king_black = King.new(7,4,'b')
queen_black = Queen.new(7,3,'b')